language: python

python: "3.6"

sudo: true

compiler:
  - clang
  - gcc

install:
  - .travis/setup_ssh.sh
  - sudo apt-get update -qq
  - sudo apt-get install -qq openssh-client openssh-server
  - cd ./udt
  - make
  - cd ../src
  - make
  - cd ..

before_script:
  - pip install -r tests/requirements.txt

script: "py.test -vv tests"
